backend:
  name: github
  repo: gloit001/hextra_test
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: auth

media_folder: "exampleSite/static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "exampleSite/content/blog"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "date", format: "YYYY-MM-DD"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "docs"
    label: "Documentation"
    folder: "exampleSite/content/docs"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  # 사이트 설정 관리
  - name: "settings"
    label: "Site Settings"
    files:
      - label: "Site Configuration"
        name: "config"
        file: "exampleSite/hugo.yaml"
        fields:
          - {label: "Site Title", name: "title", widget: "string"}
          - {label: "Base URL", name: "baseURL", widget: "string"}
          - {label: "Default Language", name: "defaultContentLanguage", widget: "string"}
          - label: "Navigation Menu"
            name: "menu"
            widget: "object"
            fields:
              - label: "Main Menu"
                name: "main"
                widget: "list"
                fields:
                  - {label: "Name", name: "name", widget: "string"}
                  - {label: "URL", name: "url", widget: "string"}
                  - {label: "Weight", name: "weight", widget: "number"}
